services:
  compose-post-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/compose-post-service.sh
    hostname: compose-post-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  home-timeline-redis:
    hostname: home-timeline-redis
    image: redis
    restart: always
  home-timeline-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/home-timeline-service.sh
    hostname: home-timeline-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  jaeger-agent:
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT="9411"
    image: jaegertracing/all-in-one:1.62.0
    ports:
    - 16686:16686
    restart: always
  media-frontend:
    depends_on:
      jaeger-agent:
        condition: service_started
    hostname: media-frontend
    image: yg397/media-frontend:xenial
    ports:
    - 8081:8080
    restart: always
    volumes:
    - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
    - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  media-memcached:
    hostname: media-memcached
    image: memcached
    restart: always
  media-mongodb:
    hostname: media-mongodb
    image: mongo:4.4.6
    restart: always
  media-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      media-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/media-service.sh
    hostname: media-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  nginx-thrift:
    depends_on:
      jaeger-agent:
        condition: service_started
    hostname: nginx-thrift
    image: yg397/openresty-thrift:xenial
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
    - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
    - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
    - ./gen-lua:/gen-lua
    - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
  post-storage-memcached:
    hostname: post-storage-memcached
    image: memcached
    restart: always
  post-storage-mongodb:
    hostname: post-storage-mongodb
    image: mongo:4.4.6
    restart: always
  post-storage-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/post-storage-service.sh
    hostname: post-storage-service
    ports:
    - 10002:9090
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  social-graph-mongodb:
    hostname: social-graph-mongodb
    image: mongo:4.4.6
    restart: always
  social-graph-redis:
    hostname: social-graph-redis
    image: redis
    restart: always
  social-graph-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/social-graph-service.sh
    hostname: social-graph-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  text-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/text-service.sh
    hostname: text-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  unique-id-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/unique-id-service.sh
    hostname: unique-id-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  url-shorten-memcached:
    hostname: url-shorten-memcached
    image: memcached
    restart: always
  url-shorten-mongodb:
    hostname: url-shorten-mongodb
    image: mongo:4.4.6
    restart: always
  url-shorten-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/url-shorten-service.sh
    hostname: url-shorten-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  user-memcached:
    hostname: user-memcached
    image: memcached
    restart: always
  user-mention-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/user-mention-service.sh
    hostname: user-mention-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  user-mongodb:
    hostname: user-mongodb
    image: mongo:4.4.6
    restart: always
  user-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/user-service.sh
    hostname: user-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
  user-timeline-mongodb:
    hostname: user-timeline-mongodb
    image: mongo:4.4.6
    restart: always
  user-timeline-redis:
    hostname: user-timeline-redis
    image: redis
    restart: always
  user-timeline-service:
    build: .
    depends_on:
      jaeger-agent:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint:
    - /social-network-microservices/./entrypoints/user-timeline-service.sh
    hostname: user-timeline-service
    restart: always
    volumes:
    - ./config:/social-network-microservices/config
version: '3.9'
